import './globals.css'

export const metadata = {
  title: 'Suno Brasil',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
      <link rel="icon" href="simbolo-suno-azul.svg" sizes="any" />
    </html>
  )
}
