import './globals.css'
import { Metadata } from 'next'
import type { Viewport } from 'next'
 
export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
}

export const metadata: Metadata  = {
  title: 'Suno Brasil',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html className="scroll-smooth" lang="en">
      <body>{children}</body>
      <link rel="icon" href="simbolo-suno-azul.svg" sizes="any" />
    </html>
  )
}
